import "./globals.css";

import type { Metadata } from "next";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
} satisfies Metadata;

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
